#!/bin/bash
# 远程 Flink 服务器配置修复脚本

echo "=== Flink 配置修复脚本 ==="
echo "请在远程 Linux 服务器上执行此脚本"
echo ""
echo "1. SSH 登录到远程服务器："
echo "   ssh etl_test@10.160.10.221"
echo ""
echo "2. 检查配置文件是否已更新："
echo "   grep 'state.checkpoints.dir' /home/etl_test/flink-1.18.1/conf/flink-conf.yaml"
echo "   grep 'state.savepoints.dir' /home/etl_test/flink-1.18.1/conf/flink-conf.yaml"
echo ""
echo "3. 如果显示的不是以下配置，请手动编辑："
echo "   vi /home/etl_test/flink-1.18.1/conf/flink-conf.yaml"
echo ""
echo "4. 确保配置内容为："
echo ""
echo "   state.checkpoints.dir: /home/etl_test/flink-1.18.1/checkpoint/checkpoints"
echo "   state.savepoints.dir: /home/etl_test/flink-1.18.1/checkpoint/savepoints"
echo ""
echo "5. 注意：配置文件中的 SQL Gateway 部分注释有问题"
echo "   将 '##' 改为 '#'"
echo ""
echo "6. 保存后重启集群："
echo "   /home/etl_test/flink-1.18.1/bin/stop-cluster.sh"
echo "   /home/etl_test/flink-1.18.1/bin/start-cluster.sh"
echo "   /home/etl_test/flink-1.18.1/bin/sql-gateway.sh restart"
